requires = ["tox>=4"]
env_list = ["type", "3.11"]

[env_run_base]
description = "run unit tests"
deps = []
commands = [["python3", "-m", "unittest", { replace = "posargs", default = ["tests"], extend = true }]]

[env.type]
description = "run type checks"
deps = ["mypy"]
commands = [["mypy", { replace = "posargs", default = ["bin/pyli", "pyli", "tests"], extend = true} ]]
